### PR TITLE
Cluster WG Roadmap

### PR DESCRIPTION
**Pull request by daviddias**
Preview: https://github.com/ipfs/roadmap/blob/roadmap-wg-cluster/WG_CLUSTER.md

### CODE REVIEW

**Comment by daviddias** [comment]
Hi IPFS Cluster Team!

Now that the Roadmap is a live PR on Github, it is a good time to check in on our Roadmap Instruction Manuals and check in to see if the Roadmap contemplates everything we could have wished for and everything we believe it is valuable for the community to have access. Think things like: Is the Vision described? Are the Requirements well understood? We have a good sense of priority and dependencies? 

You can find the Roadmap Instruction Manuals at:
- https://github.com/ipfs/team-mgmt/blob/master/ROADMAP_HOW_TO.md
- https://github.com/ipfs/team-mgmt/blob/master/TEAM_COORDINATION_TOOLKIT.md#types-of-roadmaps

Check in with your WG and have fun giving this review! :)

**Comment by hsanjuan** [comment]
Hey @meiqimichelle , can you help with this?

**Review by meiqimichelle — APPROVED** [review]
LGTM -- we reviewed this earlier, and it still reflects our roadmap and goals.

**Comment by momack2** [comment]
Merging this PR to document where we are on our roadmaps - future iterations to narrow down on a more focused and achievable set of roadmap initiatives (to match project-level priority update) will follow in next few weeks in a separate PR.

**Pull request merged**
