### PR TITLE
Community WG Roadmap

### PR DESCRIPTION
**Pull request by daviddias**
https://github.com/ipfs/roadmap/blob/roadmap-wg-community/WG_COMMUNITY.md

### CODE REVIEW

**Comment by mikeal** [comment]
Fixed :)

**Comment by terichadbourne** [comment]
Missing a word here, assuming this is meant to be "is **_in_** the community repo."  Tried to push a commit but I don't appear to have access.

>remote: Permission to ipfs/roadmap.git denied to terichadbourne.
fatal: unable to access 'https://github.com/ipfs/roadmap.git/': The requested URL returned error: 403

**Comment by mikeal** [comment]
@terichadbourne thanks, fixed :)

**Comment by daviddias** [comment]
Hi Community WG!

Now that the Roadmap is a live PR on Github, it is a good time to check in on our Roadmap Instruction Manuals and check in to see if the Roadmap contemplates everything we could have wished for and everything we believe it is valuable for the community to have access. Think things like: Is the Vision described? Are the Requirements well understood? We have a good sense of priority and dependencies? 

You can find the Roadmap Instruction Manuals at:
- https://github.com/ipfs/team-mgmt/blob/master/ROADMAP_HOW_TO.md
- https://github.com/ipfs/team-mgmt/blob/master/TEAM_COORDINATION_TOOLKIT.md#types-of-roadmaps

Check in with your WG and have fun giving this review! :)

**Comment by terichadbourne** [comment]
@daviddias Mind merging this one while @mikeal is out? I consider a month sufficient time for objections and I don't have merging powers in this repo. :)

**Comment by daviddias** [comment]
There you go :)

**Pull request merged**
